### ISSUE TITLE
@HttpTest(method = Method.POST, ...) without content leads to NullPointerException

### ISSUE THREAD

**Issue by YA2O** [eclipsesource/restfuse#42]
In com.eclipsesource.restfuse.annotation.HttpTest, the default value for content is an empty string. This content value does not work for a POST request (@HttpTest(method = Method.POST, ..., content = "")  ). 

It is an expected use case to use a HTTP POST without content; this is often the case when creating resources in a ReSTful web service, with the data for the resource provided by the server, like e.g. a timestamp (e.g. /users/john/checkin/).

Stack Trace:

java.lang.NullPointerException
    at com.github.kevinsawicki.http.HttpRequest$CloseOperation.done(HttpRequest.java:647)
    at com.github.kevinsawicki.http.HttpRequest$Operation.call(HttpRequest.java:608)
    at com.github.kevinsawicki.http.HttpRequest.copy(HttpRequest.java:2380)
    at com.github.kevinsawicki.http.HttpRequest.send(HttpRequest.java:2727)
    at com.eclipsesource.restfuse.internal.InternalRequest.post(InternalRequest.java:76)
    at com.eclipsesource.restfuse.internal.HttpTestStatement.callService(HttpTestStatement.java:119)
    at com.eclipsesource.restfuse.internal.HttpTestStatement.sendRequest(HttpTestStatement.java:105)
    at com.eclipsesource.restfuse.internal.BasicStatement.evaluate(BasicStatement.java:30)
    at com.eclipsesource.restfuse.internal.HttpTestStatement.doEvaluate(HttpTestStatement.java:84)
    at com.eclipsesource.restfuse.internal.HttpTestStatement.evaluate(HttpTestStatement.java:64)
    at org.junit.rules.RunRules.evaluate(RunRules.java:18)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)

**Comment by NehaBhatia** [comment]
We are running into the same issue. Are there any plans to merge this suggestion in?
